/* tslint:disable */
/* eslint-disable */
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LessonInfoResponse } from './lesson-info-response';

/**
 * 
 * @export
 * @interface ChapterInfoResponse
 */
export interface ChapterInfoResponse {
    /**
     * 段落的id
     * @type {number}
     * @memberof ChapterInfoResponse
     */
    'id': number;
    /**
     * 段落的标题
     * @type {string}
     * @memberof ChapterInfoResponse
     */
    'title': string;
    /**
     * 段落的描述
     * @type {string}
     * @memberof ChapterInfoResponse
     */
    'description': string;
    /**
     * 段落包含的所有课程信息
     * @type {Array<LessonInfoResponse>}
     * @memberof ChapterInfoResponse
     */
    'lessons': Array<LessonInfoResponse>;
}

