/* tslint:disable */
/* eslint-disable */
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExerciseInfoResponseItemsInner } from './exercise-info-response-items-inner';

/**
 * 
 * @export
 * @interface ExerciseInfoResponse
 */
export interface ExerciseInfoResponse {
    /**
     * 完成一次练习获取的经验值
     * @type {number}
     * @memberof ExerciseInfoResponse
     */
    'xp': number;
    /**
     * 当前练习的难度(easy/medium/hard）
     * @type {string}
     * @memberof ExerciseInfoResponse
     */
    'difficulty': string;
    /**
     * 当前练习包含的所有项目
     * @type {Array<ExerciseInfoResponseItemsInner>}
     * @memberof ExerciseInfoResponse
     */
    'items': Array<ExerciseInfoResponseItemsInner>;
}

