// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 简短翻译
     * @type {string}
     * @memberof InlineResponse200
     */
    simple_trans: string;
    /**
     * 复杂释义
     * @type {string}
     * @memberof InlineResponse200
     */
    more_trans: string;
}


