// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse200Sections
 */
export interface InlineResponse200Sections {
    /**
     * 章节id
     * @type {number}
     * @memberof InlineResponse200Sections
     */
    id: number;
    /**
     * 章节标题
     * @type {string}
     * @memberof InlineResponse200Sections
     */
    title: string;
    /**
     * 当前章节包含的所有练习id
     * @type {Array<number>}
     * @memberof InlineResponse200Sections
     */
    exercises: Array<number>;
}


