// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VideoExercise } from './video-exercise';

/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * 完成一次练习获取的经验值
     * @type {number}
     * @memberof InlineResponse2003
     */
    xp: number;
    /**
     * 当前练习的难度(easy/medium/hard）
     * @type {string}
     * @memberof InlineResponse2003
     */
    difficulty: string;
    /**
     * 当前练习包含的所有项目
     * @type {Array<VideoExercise | object>}
     * @memberof InlineResponse2003
     */
    items: Array<VideoExercise | object>;
}


