// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 一个 .txt 格式的文本文件，内容为待对比的英文摘要。
     * @type {any}
     * @memberof InlineObject
     */
    summary_txt_file?: any;
    /**
     * 用户的录音文件，支持 .mp3, .wav, .m4a 等主流音频格式。
     * @type {any}
     * @memberof InlineObject
     */
    user_audio?: any;
}


