// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 段落的标题
     * @type {string}
     * @memberof InlineResponse2001
     */
    title: string;
    /**
     * 段落的描述
     * @type {string}
     * @memberof InlineResponse2001
     */
    description: string;
    /**
     * 段落包含的所有课程的id
     * @type {Array<number>}
     * @memberof InlineResponse2001
     */
    lessons: Array<number>;
}


