// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LessonInfoResponse
 */
export interface LessonInfoResponse {
    /**
     * 课程的id
     * @type {number}
     * @memberof LessonInfoResponse
     */
    id: number;
    /**
     * 课程的描述
     * @type {string}
     * @memberof LessonInfoResponse
     */
    description: string;
    /**
     * 当前课程下的所有练习题id列表
     * @type {Array<number>}
     * @memberof LessonInfoResponse
     */
    exercises: Array<number>;
}


