/* tslint:disable */
/* eslint-disable */
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SectionInfoResponse } from './section-info-response';

/**
 * 
 * @export
 * @interface SectionListResponse
 */
export interface SectionListResponse {
    /**
     * 章节列表
     * @type {Array<SectionInfoResponse>}
     * @memberof SectionListResponse
     */
    'sections': Array<SectionInfoResponse>;
}

