// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VideoExercise
 */
export interface VideoExercise {
    /**
     * 类型标识符，必须为Video
     * @type {string}
     * @memberof VideoExercise
     */
    type: string;
    /**
     * 这个实体的id
     * @type {number}
     * @memberof VideoExercise
     */
    id: number;
    /**
     * 相应的视频的URL
     * @type {string}
     * @memberof VideoExercise
     */
    video: string;
    /**
     * 相应的视频对应的字幕文件（SRT格式）的URL
     * @type {string}
     * @memberof VideoExercise
     */
    srt: string;
}


