/* tslint:disable */
/* eslint-disable */
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WordlistRandomwordGet200Response
 */
export interface WordlistRandomwordGet200Response {
    /**
     * 随机单词1，返回一个单词表内的随机单词
     * @type {string}
     * @memberof WordlistRandomwordGet200Response
     */
    'word1': string;
    /**
     * 随机单词2
     * @type {string}
     * @memberof WordlistRandomwordGet200Response
     */
    'word2': string;
    /**
     * 随机单词3
     * @type {string}
     * @memberof WordlistRandomwordGet200Response
     */
    'word3': string;
    /**
     * 随机单词4
     * @type {string}
     * @memberof WordlistRandomwordGet200Response
     */
    'word4': string;
}

