// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WordlistFetchInfoResponse
 */
export interface WordlistFetchInfoResponse {
    /**
     * 本次获取的单词数量
     * @type {number}
     * @memberof WordlistFetchInfoResponse
     */
    number?: number;
    /**
     * 获取到的单词列表
     * @type {Array<string>}
     * @memberof WordlistFetchInfoResponse
     */
    list: Array<string>;
    /**
     * 是否还有更多单词
     * @type {boolean}
     * @memberof WordlistFetchInfoResponse
     */
    hasNextPage: boolean;
    /**
     * 下一个单词
     * @type {string}
     * @memberof WordlistFetchInfoResponse
     */
    nextWord: string | null;
}


