/* tslint:disable */
/* eslint-disable */
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WordlistTranslateGet200Response
 */
export interface WordlistTranslateGet200Response {
    /**
     * 简短翻译
     * @type {string}
     * @memberof WordlistTranslateGet200Response
     */
    'simple_trans': string;
    /**
     * 复杂释义
     * @type {string}
     * @memberof WordlistTranslateGet200Response
     */
    'more_trans': string;
}

