/* tslint:disable */
/* eslint-disable */
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorksheetFetchInfoResponse
 */
export interface WorksheetFetchInfoResponse {
    /**
     * 获取到的单词列表，第一个单词是正确答案
     * @type {Array<string>}
     * @memberof WorksheetFetchInfoResponse
     */
    'list': Array<string>;
    /**
     * 是否还有更多单词
     * @type {boolean}
     * @memberof WorksheetFetchInfoResponse
     */
    'hasNextPage': boolean;
    /**
     * 下一个单词
     * @type {string}
     * @memberof WorksheetFetchInfoResponse
     */
    'nextWord': string | null;
    /**
     * 正确单词对应的中文翻译
     * @type {string}
     * @memberof WorksheetFetchInfoResponse
     */
    'translation': string;
}

