// tslint:disable
/**
 * Vilingo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
import axios from "axios";
import { DefaultApi } from "./api";
import { Configuration } from "./configuration";


// 1. 创建一个自定义的 axios 实例，以便添加拦截器等
const axiosInstance = axios.create({
  // 你可以在这里添加 baseURL，但生成代码的配置更优先
});

// 2. 创建 API 配置对象
const apiConfig = new Configuration({
  // 这个 basePath 会覆盖生成代码中的默认值
  basePath: 'https://your-api.vilingo.com', 
});

// 3. 实例化你的 API 客户端，并传入配置和 axios 实例
//    这就是你将在整个应用中使用的 API 对象
export const apiClient = new DefaultApi(apiConfig, undefined, axiosInstance);
